### ISSUE TITLE
UI for security stuff

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/plugin-mobicage-control-center#3]
---

Migrated from https://github.com/rogerthat-platform/plugin-rogerthat-control-center/issues/277
Originally created by @lucasvanhalst on *Mon, 14 May 2018 15:37:19 GMT*

---
Add ui for changing 'security' stuff in build.yaml

defaults:
```yaml
  SECURITY:
    APP_KEY_ALGORITHM: ed25519
    APP_KEY_NAME: threefold
    PIN_LOCKED: true
    SECURE: true
```

Remove 'SECURE' from build.yaml in old files , but I think there's already a migration which does that
