### ISSUE TITLE
Add joyn to build.yaml in new belgium city apps

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/plugin-mobicage-control-center#31]
Only for BE city apps
- [x] Add joyn to toolbar
- [x] Add joyn translations

Example:
```yaml
TOOLBAR:
  items:
  - action: reserve1
    action_type: action
    color: null
    icon: fa-cutlery
    params: {}
    text: Reserve
  - action: __sln__.order
    action_type: action
    color: null
    icon: fa-shopping-cart
    params: {}
    text: Order
  - action: app
    action_type: open
    icon: joyn
    params:
      android_app_id: com.thanksys.joyn.user
      android_scheme: joyn://
      ios_app_id: id1157594279
      ios_scheme: joyn://
    text: Joyn Loyalty
  - action: qrcode
    action_type: null
    color: null
    icon: fa-credit-card
    params: {}
    text: QR code
TRANSLATIONS:
  en:
  - name: local_news
    value: Local News
  - name: regional_news
    value: Regional News
  - name: joyn_loyalty
    value: Joyn Loyalty
  nl:
  - name: local_news
    value: Lokaal Nieuws
  - name: regional_news
    value: Regionaal Nieuws
  - name: joyn_loyalty
    value: Joyn Loyalty

```
